#!/bin/bash

BASEDIR=$(dirname "$0")

cp=$(readlink -f "$BASEDIR/../target/fish-reg-jar-with-dependencies.jar")
echo $cp

java -cp "$cp" -Xmx16g org.janelia.saalfeldlab.matching.MultiHypothesisZarr $@
